package com.example.dynamodbdemo.dao.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@DynamoDBTable(tableName = "ProductInfo")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ProductInfo {
  private String id;
  private String msrp;
  private String cost;

  public ProductInfo(String msrp, String cost) {
    this.msrp = msrp;
    this.cost = cost;
  }

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return id;
  }

  @DynamoDBAttribute
  public String getMsrp() {
    return msrp;
  }

  @DynamoDBAttribute
  public String getCost() {
    return cost;
  }

  // standard setters/constructors
}
